project:
  type: book
  output-dir: docs

book:
  title: "The Geospatial Neighborhood Analysis Package"
  author: "Elijah Knaap"
  date: "1/15/2024"
  cover-image: images/geosnap.svg
  search: true
  repo-url: https://github.com/oturns/geosnap/
  repo-actions: [edit, source]
  #downloads: [pdf, epub]
  sharing: [twitter]
  open-graph:
    image: "images/geosnap_long.png"
    title: A Guide to Geosnap
    site-name: The Geospatial Neighborhood Analysis Package
  favicon: images/geosnap.ico
  page-footer:
    center: 
      - text: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://oturns.github.io/geosnap-guide">A Guide to Geosnap</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://knaaptime.com">elijah knaap</a> is licensed under <a href="http://creativecommons.org/licenses/by-nc-nd/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-ND 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nd.svg?ref=chooser-v1"></a></p>
  twitter-card:
    creator: "@knaaptime"
    site: "@knaaptime"

  google-analytics: "G-0PG1JNLCXB"
  url: "https://oturns.github.io.geosnap-guide"
  site-url: "https://oturns.github.io.geosnap-guide"

  sidebar:
    style: floating
    logo: "images/geosnap_long.png"

  comments:
    hypothesis: true
  chapters:
    - index.md
    - datasets.ipynb
    - harmonization.ipynb
    - clustering.ipynb
    - regionalization.ipynb
    - dynamics.ipynb
    - segregation_dynamics.ipynb
    - isochrone_example.ipynb

bibliography: geosnap.bib


format:
  html:
    theme: 
      light: sandstone
      dark: cyborg
    output-dir: docs
    code-tools: true
    code-fold: show
    code-copy: hover

website:
  image: "images/geosnap_long.png"
  title: A Guide to Geosnap
